
-- Erste queries für die Tierdatenbank
-- 1. Cleanup
DROP TABLE IF EXISTS loans CASCADE;
DROP TABLE IF EXISTS object_images CASCADE;
DROP TABLE IF EXISTS collect_items CASCADE;
DROP TABLE IF EXISTS storage_locations CASCADE;
DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS geo_locations CASCADE;
DROP TABLE IF EXISTS taxonomy CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. Users (Clerk Integration)
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clerk_id TEXT UNIQUE NOT NULL, -- Verbindung zu Clerk
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT CHECK (role IN ('Admin', 'Moderator', 'Nutzer')) DEFAULT 'Nutzer',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Taxonomy
CREATE TABLE taxonomy (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id INTEGER REFERENCES taxonomy(id) ON DELETE RESTRICT,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL, -- Geändert: SET NULL falls User gelöscht wird
    name TEXT NOT NULL,
    rank TEXT CHECK (rank IN ('Reich', 'Stamm', 'Klasse', 'Ordnung', 'Familie', 'Gattung', 'Art')), 
    is_approved BOOLEAN DEFAULT false,
    CONSTRAINT unique_taxonomy_name_parent UNIQUE (name, parent_id)
);

-- Root-Eintrag (is_approved ist TRUE, da System-Eintrag)
INSERT INTO taxonomy (name, rank, is_approved) 
VALUES ('Animalia', 'Reich', true);

-- 4. Geo_Locations
CREATE TABLE geo_locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id INTEGER REFERENCES geo_locations(id) ON DELETE RESTRICT,
    external_id TEXT UNIQUE, 
    name TEXT NOT NULL,
    latitude DECIMAL(9,6),
    longitude DECIMAL(9,6),
    type TEXT 
);

-- 5. Collections
CREATE TABLE collections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, 
    name TEXT NOT NULL,
    description TEXT,
    is_public BOOLEAN DEFAULT false
);

-- 6. Collect_Items
CREATE TABLE collect_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id INTEGER REFERENCES collections(id) ON DELETE CASCADE,
    taxonomy_id INTEGER REFERENCES taxonomy(id) ON DELETE SET NULL,
    finding_location_id INTEGER REFERENCES geo_locations(id) ON DELETE SET NULL,
    name TEXT,
    find_date DATE,
    description TEXT,
    storage_info TEXT, 
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Object_Images
CREATE TABLE object_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id INTEGER REFERENCES collect_items(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL, -- Der Link Cloudinary
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 8. Loans
CREATE TABLE loans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id INTEGER REFERENCES collect_items(id) ON DELETE CASCADE,
    lender_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    borrower_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    start_date DATE,
    end_date DATE,
    status TEXT CHECK (status IN ('offen', 'zurückgegeben')) DEFAULT 'offen'
);

-- 9. Performance Indexe
CREATE INDEX idx_users_clerk_id ON users(clerk_id);
CREATE INDEX idx_items_collection ON collect_items(collection_id);
CREATE INDEX idx_items_taxonomy ON collect_items(taxonomy_id);
CREATE INDEX idx_taxonomy_parent ON taxonomy(parent_id);
CREATE INDEX idx_geo_parent ON geo_locations(parent_id);
CREATE INDEX idx_loans_object ON loans(object_id);

-- Update:
-- Vorname und Nachname der Nutzer hinzufügen.
ALTER TABLE users
ADD COLUMN first_name text,
ADD COLUMN last_name text;

-- Update:
-- biologische Daten der Collect_Items hinzufügen: Geschlecht, Altersklasse, Körpermasse und Körperlänge.
ALTER TABLE collect_items
ADD COLUMN sex text,
ADD COLUMN age_class text,
ADD COLUMN body_mass_gram numeric(10,2),
ADD COLUMN body_length_mm numeric(10,2);


-- Update:
-- Taxonomien Einreichung durch Nutzer: Neue Tabelle für Einreichungen, die von Moderatoren geprüft werden müssen.
-- getrennt von der Haupt-Taxonomie-Tabelle, um die Integrität der bestehenden Taxonomien zu gewährleisten.

CREATE TABLE taxonomy_submissions (
    id SERIAL PRIMARY KEY,
    created_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL,

    reich TEXT NOT NULL DEFAULT 'Animalia',
    stamm TEXT NOT NULL,
    klasse TEXT NOT NULL,
    ordnung TEXT NOT NULL,
    familie TEXT NOT NULL,
    gattung TEXT NOT NULL,
    art TEXT NOT NULL,

    source TEXT NOT NULL DEFAULT 'manual',
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),

    moderator_note TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    reviewed_at TIMESTAMP NULL,
    reviewed_by INTEGER NULL REFERENCES users(id) ON DELETE SET NULL
);


--Update:
-- Nutzersperrung und Soft-Delete für Nutzerkonten hinzufügen.
ALTER TABLE users
ADD COLUMN is_banned boolean NOT NULL DEFAULT false;

ALTER TABLE users
ADD COLUMN deleted_at timestamp with time zone NULL;

-- Update:
-- Tabellenänderungen für die Tabelle mit Bildern von Objekten: 
--Bild-URL optional machen, neue Spalten für Bilddaten hinzufügen, 
--und eine CHECK-Constraint, dass entweder die URL oder die Bilddaten gesetzt sind, 
--aber nicht beide gleichzeitig

ALTER TABLE object_images
    ALTER COLUMN image_url DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS image_data bytea,
    ADD COLUMN IF NOT EXISTS content_type varchar(100),
    ADD COLUMN IF NOT EXISTS original_file_name text,
    ADD COLUMN IF NOT EXISTS byte_size bigint;

ALTER TABLE object_images
    ADD CONSTRAINT ck_object_images_single_storage
    CHECK (
        (image_url IS NOT NULL AND image_data IS NULL)
        OR
        (image_url IS NULL AND image_data IS NOT NULL)
    );


-- Update:
-- Verhindert, dass ein Objekt (loans.object_id) gleichzeitig mehr als eine
-- offene Leihe (status = 'offen') hat. Schließt die Race Condition, bei der
-- zwei parallele POST /api/loan-Requests dasselbe Objekt doppelt verleihen.

CREATE UNIQUE INDEX IF NOT EXISTS idx_loans_object_open_unique
ON loans (object_id)
WHERE status = 'offen';

--Update:
-- neue Sparte für collect_items: "created_by_user_id" (FK zu users.id)
-- Speichert, welcher Nutzer ein collect_items-Objekt (Tier) angelegt hat.
-- Grundlage für die Lösch-Berechtigung "nur Admin, Moderator oder Ersteller"
-- in AnimalsController.DeleteAnimal.
ALTER TABLE collect_items
    ADD COLUMN IF NOT EXISTS created_by_user_id integer REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_collect_items_created_by ON collect_items(created_by_user_id);

--Update:
-- Fügt eine zweite, vom Verleiher unabhängige Freigabestufe durch Moderator/Admin hinzu, bevor
-- eine Leihe aktiv wird: neuer Zwischenstatus 'in_pruefung'. Sowohl der direkte Verleih durch den
-- Eigentümer als auch eine vom Verleiher bestätigte Anfrage landen jetzt zunächst hier, statt sofort
-- auf 'offen' zu springen (siehe LoanController.CreateLoan / ApproveLoanRequest / ModerateApprove).
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        WHERE rel.relname = 'loans' AND con.contype = 'c'
          AND pg_get_constraintdef(con.oid) ILIKE '%status%'
    LOOP
        EXECUTE format('ALTER TABLE loans DROP CONSTRAINT %I', r.conname);
    END LOOP;
END $$;

ALTER TABLE loans
    ADD CONSTRAINT loans_status_check
    CHECK (status IN ('angefragt', 'in_pruefung', 'offen', 'abgelehnt', 'zurückgegeben'));

-- Der bisherige Unique-Index verhinderte nur zwei gleichzeitig *aktive* ('offen') Leihen für
-- dasselbe Objekt. Da ein Objekt jetzt schon während der Moderationsprüfung ('in_pruefung')
-- reserviert ist, muss der Index diesen Status ebenfalls abdecken.
DROP INDEX IF EXISTS idx_loans_object_open_unique;
CREATE UNIQUE INDEX IF NOT EXISTS idx_loans_object_open_unique
ON loans (object_id)
WHERE status IN ('offen', 'in_pruefung');